name: Mlog By ME
favicon: null
layout_spectrum: 0.75284
typography_spectrum: 0.67827
title: Mlog - En musiklogg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74187173-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070304'
    - '#f9f8f3'
    - '#4a3a2b'
    - '#aab2c5'
    - '#c85c1c'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
