typography_spectrum: 0.027453386690467596
color:
  brandColors:
    - '#070304'
    - '#f9f8f3'
    - '#4a3a2b'
    - '#aab2c5'
    - '#c85c1c'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.648098980076611
analytics:
  google: UA-74187173-1
  facebook: null
  twitter: null
name: Mlog By ME
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Mlog
description: En musiklogg
purpose: []
